"""
Django settings for DjangoUserService project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

import pymysql
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('JWT_SECRET_KEY') or os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,django").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',

    
    'apps.user.apps.UserConfig',
    'apps.file',
    'apps.ops.apps.OpsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoUserService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoUserService.wsgi.application'

# settings.py
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 数据库后端短名称 → Django 完整路径映射
DB_ENGINE_MAP = {
    'mysql': 'django.db.backends.mysql',
    'postgresql': 'django.db.backends.postgresql',
    'sqlite3': 'django.db.backends.sqlite3',
    'oracle': 'django.db.backends.oracle',
}

raw_engine = os.getenv('DB_ENGINE', 'mysql')
# 支持短名称 (mysql)、已有完整路径 (django.db.backends.xxx) 或其他自定义
if raw_engine in DB_ENGINE_MAP:
    db_engine = DB_ENGINE_MAP[raw_engine]
elif raw_engine.startswith('django.db.backends.'):
    db_engine = raw_engine
else:
    db_engine = f'django.db.backends.{raw_engine}'

DATABASES = {
    'default': {
        'ENGINE': db_engine,
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# 仅 MySQL 才设置 utf8mb4 选项
if db_engine == 'django.db.backends.mysql':
    DATABASES['default']['OPTIONS'] = {
        'charset': 'utf8mb4',
        'use_unicode': True,
        'init_command': 'SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci',
    }

# FastAPI 使用独立的 chat_history 数据库；Django Admin 只读访问其中的业务表。
backend_database = DATABASES['default'].copy()
backend_database['NAME'] = os.getenv(
    'BACKEND_DB_NAME',
    'chat_history' if db_engine == 'django.db.backends.mysql' else DATABASES['default']['NAME'],
)
if 'OPTIONS' in DATABASES['default']:
    backend_database['OPTIONS'] = DATABASES['default']['OPTIONS'].copy()
if db_engine != 'django.db.backends.mysql':
    backend_database['TEST'] = {'MIRROR': 'default'}
DATABASES['backend'] = backend_database

DATABASE_ROUTERS = ['apps.ops.db_router.BackendDatabaseRouter']
MIGRATION_MODULES = {'ops': None}

# 使用 MySQL 时，用 PyMySQL 模拟 MySQLdb
if db_engine == 'django.db.backends.mysql':
    pymysql.install_as_MySQLdb()

# Celery 配置
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
# 统一时区设置
CELERY_TIMEZONE = 'Asia/Shanghai'
# 启用UTC
CELERY_ENABLE_UTC = False
# 设置任务队列
CELERY_TASK_QUEUES = {
    'default': {
        'exchange': 'default',
        'routing_key': 'default',
    },
    'email': {
        'exchange': 'email',
        'routing_key': 'email.tasks',
    }
}
# 设置任务路由
CELERY_TASK_ROUTES = {
}
# 任务执行超时时间（秒）
CELERY_TASK_TIME_LIMIT = 10
# 任务软超时时间（秒）
CELERY_TASK_SOFT_TIME_LIMIT = 8
# 任务结果过期时间（秒）
CELERY_RESULT_EXPIRES = 3600

if os.getenv('REDIS_CACHE_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_CACHE_URL'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'rag-notebook-local-cache',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# 语言编码
LANGUAGE_CODE = 'zh-hans'

# 统一使用上海时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
# 禁用时区支持，与Celery配置保持一致
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

BACKEND_API_URL = os.getenv('BACKEND_API_URL', 'http://127.0.0.1:8000')
BACKEND_STATUS_TIMEOUT = float(os.getenv('BACKEND_STATUS_TIMEOUT', '3'))
BACKEND_LOG_DIR = os.getenv('BACKEND_LOG_DIR', str(BASE_DIR.parent / 'backend' / 'logs'))
BACKEND_LOG_MAX_LINES = max(50, min(int(os.getenv('BACKEND_LOG_MAX_LINES', '500')), 2000))

# 允许所有域名跨域访问
CORS_ALLOW_ALL_ORIGINS = True

# 覆盖默认的用户模型
AUTH_USER_MODEL = 'user.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.user.authentications.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 权限类
    ],
    # 3. 全局分页
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 每页默认显示数量
    'PAGE_SIZE': 10
}

APPEND_SLASH = True
